codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 5%
        base: auto

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*Tests/**"
  - "**/Tests/**"
  - "**/*.Tests/**"
  - "**/Benchmarks/**"
  - "**/*.Benchmarks/**"
  - "**/*.E2ETests/**"
  - "**/E2ETests/**"
  - "**/obj/**"
  - "**/bin/**"
