codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
        base: auto
        if_ci_failed: error
      core:
        target: 90%
        paths:
          - "src/Core/**"
        if_ci_failed: error
      communication:
        target: 90%
        paths:
          - "src/Infrastructure/ZakYip.WheelDiverterSorter.Communication/**"
        if_ci_failed: error
      execution:
        target: 90%
        paths:
          - "src/Execution/**"
        if_ci_failed: error
      host:
        target: 90%
        paths:
          - "src/Host/**"
        if_ci_failed: error
    patch:
      default:
        target: 85%
        threshold: 2%
        base: auto
        if_ci_failed: error

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*Tests/**"
  - "**/Tests/**"
  - "**/*.Tests/**"
  - "**/Benchmarks/**"
  - "**/*.Benchmarks/**"
  - "**/*.E2ETests/**"
  - "**/E2ETests/**"
  - "**/obj/**"
  - "**/bin/**"
